
### ユーザー登録
POST http://localhost:8000/api/register
content-type: application/json
Accept: application/json

{
    "name": "sample11",
    "level": 21,
    "exp": 210,
    "life": 1,
    "password": "jobi"
}

### ユーザーログイン
POST http://localhost:8000/api/login
content-type: application/json
Accept: application/json

{
    "name": "sample10",
    "password": "jobi"
}

### ユーザー情報取得
GET http://localhost:8000/api/users/56?withItems=true&withMails=true
Accept: application/json
Authorization: Bearer 1|5dmNRiHMnfRhkx6HDMpbcAqd1Uv295rSs4viCtlj552935c1

### ユーザー情報取得(Level指定)
GET http://localhost:8000/api/users/?min_level=3&max_level=30
content-type: application/json
Accept: application/json
Authorization: Bearer 1|yIkN5VDijd5ZqZmRQP8NLnANong5bbbm0XXUaTzo71b12308

### ユーザー情報更新
POST http://localhost:8000/api/users/update
content-type: application/json
Authorization: Bearer 1|yIkN5VDijd5ZqZmRQP8NLnANong5bbbm0XXUaTzo71b12308
Accept: application/json

{
    "life": 2
}

### フォロー取得
GET http://localhost:8000/api/follows/56
content-type: application/json
Authorization: Bearer 1|yIkN5VDijd5ZqZmRQP8NLnANong5bbbm0XXUaTzo71b12308
Accept: application/json

### フォロー追加
POST http://localhost:8000/api/follows/store
content-type: application/json
Authorization: Bearer 1|yIkN5VDijd5ZqZmRQP8NLnANong5bbbm0XXUaTzo71b12308
Accept: application/json

{
    "follow_user_id": 23
}

### フォロー削除
POST http://localhost:8000/api/follows/destroy
content-type: application/json
Authorization: Bearer 1|yIkN5VDijd5ZqZmRQP8NLnANong5bbbm0XXUaTzo71b12308
Accept: application/json

{
    "follow_user_id": 23
}

### アイテム取得
GET http://localhost:8000/api/items
Authorization: Bearer 2|CavqEDhXShr9qcC4ADneQaX1FRhrWtjvUZLia3qf1671e570
Accept: application/json

### ユーザーアイテム追加更新
POST http://localhost:8000/api/items/store
content-type: application/json
Authorization: Bearer 1|yIkN5VDijd5ZqZmRQP8NLnANong5bbbm0XXUaTzo71b12308
Accept: application/json

{
    "item_id": 2,
    "amount": 3
}

### ユーザー受信メール開封
POST http://localhost:8000/api/mails/update
content-type: application/json
Authorization: Bearer 1|yIkN5VDijd5ZqZmRQP8NLnANong5bbbm0XXUaTzo71b12308
Accept: application/json

{
    "mail_id": 3,
    "received": 1
}

### ステージ取得
GET http://localhost:8000/api/stages
content-type: application/json
Authorization: Bearer 1|5dmNRiHMnfRhkx6HDMpbcAqd1Uv295rSs4viCtlj552935c1
Accept: application/json

### ユーザーステージ状況更新
POST http://localhost:8000/api/stages/store
content-type: application/json
Authorization: Bearer 1|5tMx5Cr9a3bMT9P1lJr36xpF07vuL27mevR4Lp3o869e53c3
Accept: application/json

{
    "stage_id": 1,
    "time": 6
}

### ユーザーステージ状況取得
GET http://localhost:8000/api/stages/56
content-type: application/json
Accept: application/json

### ステージレコード取得
GET http://localhost:8000/api/stages/record
content-type: application/json
Accept: application/json

{
    "user_id": 1,
    "stage_id": 1
}
