
### ユーザー登録
POST http://4.241.169.185/api/register
content-type: application/json
Accept: application/json

{
    "name": "sample23",
    "level": 21,
    "exp": 210,
    "life": 1,
    "password": "jobi"
}

### ユーザーログイン
POST http://4.241.169.185/api/login
content-type: application/json
Accept: application/json

{
    "name": "sample10",
    "password": "jobi"
}

### ユーザー情報取得
GET http://4.241.169.185/api/users/43?withItems=true&withMails=true
Accept: application/json
Authorization: Bearer 7|SQEguMlvX6ix9WlKuJUyHQYqbyMOyc4nAqxM1SYl9b89952d

### ユーザー情報取得(Level指定)
GET http://localhost:8000/api/users/?min_level=3&max_level=30
content-type: application/json
Accept: application/json
Authorization: Bearer 1|yIkN5VDijd5ZqZmRQP8NLnANong5bbbm0XXUaTzo71b12308

### ユーザー情報更新
POST http://localhost:8000/api/users/update
content-type: application/json
Authorization: Bearer 1|yIkN5VDijd5ZqZmRQP8NLnANong5bbbm0XXUaTzo71b12308
Accept: application/json

{
    "life": 2
}

### フォロー取得
GET http://localhost:8000/api/follows/56
content-type: application/json
Authorization: Bearer 1|yIkN5VDijd5ZqZmRQP8NLnANong5bbbm0XXUaTzo71b12308
Accept: application/json

### フォロー追加
POST http://localhost:8000/api/follows/store
content-type: application/json
Authorization: Bearer 1|yIkN5VDijd5ZqZmRQP8NLnANong5bbbm0XXUaTzo71b12308
Accept: application/json

{
    "follow_user_id": 23
}

### フォロー削除
POST http://localhost:8000/api/follows/destroy
content-type: application/json
Authorization: Bearer 1|yIkN5VDijd5ZqZmRQP8NLnANong5bbbm0XXUaTzo71b12308
Accept: application/json

{
    "follow_user_id": 23
}

### アイテム情報取得
GET http://48.218.51.39/api/items
Accept: application/json
Authorization: Bearer 3|NMbgCNf7eThVbVueuI9yo0glfjElP6E53wQmlhOj38a6707d

### ユーザーアイテム追加更新
POST http://48.218.51.39/api/items/store
content-type: application/json
Authorization: Bearer 3|NMbgCNf7eThVbVueuI9yo0glfjElP6E53wQmlhOj38a6707d
Accept: application/json

{
    "item_id": 2,
    "amount": 3
}

### ユーザー受信メール開封
POST http://48.218.51.39/api/mails/update
content-type: application/json
Authorization: Bearer 3|NMbgCNf7eThVbVueuI9yo0glfjElP6E53wQmlhOj38a6707d
Accept: application/json

{
    "mail_id": 1,
    "received": 1
}
